### ISSUE TITLE
Code crash

### ISSUE THREAD

**Issue by Sugz** [d0sboots/dyson-sphere-program#1]
Hello, there is an issue with dysonsphere.py:
```
Reading data... Traceback (most recent call last):
  File "dyson_wiki.py", line 632, in <module>
    main()
  File "dyson_wiki.py", line 597, in main
    data = dysonsphere.load_all()
  File "dysonsphere.py", line 531, in load_all
    result = dict((x, load_data(x, path.join(root_dir, x + '.dat')))
  File "dysonsphere.py", line 531, in <genexpr>
    result = dict((x, load_data(x, path.join(root_dir, x + '.dat')))
  File "dysonsphere.py", line 518, in load_data
    return cls(*reader.get_funcs())
  File "<dynamic StringProtoSet code>", line 17, in __init__
  File "<dynamic StringProtoSet code>", line 17, in <listcomp>
  File "<dynamic StringProto code>", line 13, in __init__
ValueError: read length must be non-negative or -1
```

**Comment by d0sboots** [comment]
Thank you for reporting! Interestingly, that's not where it was failing for me...

Regardless, the issue is because they added stuff to their serialized format with the Jan 20 major update. That happens from time to time (not as often as data changes, but it _does_ happen), requiring minor code tweaks.

I've updated the code and also updated the data template on the wiki. I'll be working through the backlog of new pages that need to be created shortly.

**Comment by Sugz** [comment]
Great, thanks for the fast fix !
